name: Resize SVGs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  resize_svgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install lxml
          npm install -g svgo

      - name: Resize SVGs
        run: |
          sudo python .github/scripts/resize-logos.py static/logos 64

      - name: Optimize SVGs with SVGO
        run: |
          svgo -f static/logos -r -o static/logos

      - name: Commit and push changes
        run: |
          git config user.name "action@github.com"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Resize SVGs to height 64px"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
