name: Resize SVGs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  resize_svgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cairosvg

      - name: Resize SVGs
        run: |
          python3 .github/scripts/resize_svgs.py ./static/logos 64

      - name: Install SVGO & convert
        run: |
          yarn global add svgo
          svgo -f static/logos -r -o static/logos

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./static/logos/*.svg
          git commit -m "Resize SVGs to height 64px"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
